language: node_js

node_js:
  - 'node'
  - '11'
  - '12'

branches:
  only:
  - /.*/

install:

cache:
  directories:
    - node_modules

git:
  depth: 1

script:
  - git clone https://github.com/AnyhowStep/tsql.git
  - cd tsql
  - npm install
  - npm run build
  - cd ../
  - npm link ./tsql
  - npm install
  - npm link ./tsql
  - npm run sanity-check-travis
  # - npm install codecov

after_success:
  # - ./node_modules/.bin/c8 report --reporter=text-lcov | ./node_modules/.bin/codecov --pipe
